# Generated by Django 4.0.1 on 2022-02-01 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=30)),
                ('phone', models.IntegerField()),
                ('password', models.CharField(max_length=20)),
                ('c_password', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Registrations',
            },
        ),
    ]
